extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/**/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.ssa]
pipeline = [
    "bril2json",
    "cargo run -q --release --bin to_ssa",
    "brili -p {args}",
]

[runs.ssa_roundtrip]
pipeline = [
    "bril2json",
    "cargo run -q --release --bin to_ssa",
    "cargo run -q --release --bin from_ssa",
    "brili -p {args}",
]
